#!/bin/sh
set -e
DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:/bin:/usr/bin:/usr/ucb
export PATH
if test -d "lz4-$VERSION"; then cd "lz4-$VERSION"; fi
patch -p1 < "lz4-$VERSION-openstep.patch"
make_lz4() {
    /usr/local/bin/gnumake CC=/usr/local/bin/gcc-4.2 SHELL=/usr/local/bin/ksh \
        CFLAGS='-O2 -march=i486 -D_POSIX_SOURCE -DCLOCKS_PER_SEC=CLK_TCK -I/NextDeveloper/Headers/bsd' \
        DEBUGFLAGS= TARGET_OS=OPENSTEP UNAME=true POSIX_ENV=Yes ARFLAGS=rc \
        BUILD_SHARED=no INSTALL=/usr/local/bin/install "$@"
}
cd lib
make_lz4 liblz4.a
/bin/ranlib liblz4.a
make_lz4 install DESTDIR="$DESTDIR" PREFIX=/usr/local
/bin/ranlib "$DESTDIR/usr/local/lib/liblz4.a"
cd ../programs
make_lz4 lz4
make_lz4 install DESTDIR="$DESTDIR" PREFIX=/usr/local
