#!/bin/sh
set -e
DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin
CC=/usr/local/bin/gcc-4.2
# PKG_WGET_OPT overrides the optimization flags (gcc 4.2 on SPARC has
# miscompiled other packages at -O2).
CFLAGS="$PKG_GCC42_ARCH_FLAGS ${PKG_WGET_OPT--O2} -std=gnu99"
CPPFLAGS=-I/usr/local/include
LDFLAGS=-L/usr/local/lib
GREP=/usr/local/bin/grep
EGREP='/usr/local/bin/grep -E'
AWK=/usr/local/bin/gawk
SED=/usr/local/bin/sed
export PATH CC CFLAGS CPPFLAGS LDFLAGS GREP EGREP AWK SED
. "$PKG_BUILD_HELPERS"

# HTTPS goes through the OpenSSL package; its default certificate bundle is
# /usr/local/ssl/cert.pem, which the ca-certificates package installs.  The
# rest is switched off: OPENSTEP has no pthreads, IPv6 or xattr, and the
# optional libraries (libpsl, PCRE, IDN) are not packaged.
run_configure --prefix=/usr/local \
  --build=$PKG_TARGET --host=$PKG_TARGET \
  --disable-nls --disable-ipv6 --disable-threads --disable-rpath \
  --disable-pcre --disable-pcre2 --disable-iri --disable-ntlm \
  --disable-xattr --disable-opie \
  --without-libpsl --without-libuuid --without-metalink --without-cares \
  --with-zlib --with-ssl=openssl --with-libssl-prefix=/usr/local

# Build only the library and the program: the manual needs makeinfo and
# pod2man newer than OPENSTEP's.
/bin/gnumake -C lib
/bin/gnumake -C src

PREFIX="$DESTDIR/usr/local"
/usr/local/bin/mkdir -p "$PREFIX/bin" "$PREFIX/etc" "$PREFIX/share/info"
/bin/cp src/wget "$PREFIX/bin/wget"
/bin/cp doc/sample.wgetrc "$PREFIX/etc/wgetrc.dist"
/bin/cp doc/wget.info "$PREFIX/share/info/wget.info"
