#!/bin/sh

set -e

TOP="$ROOT_DIR/usr/local/bin/top"

[ -x "$TOP" ]
output=`"$TOP" -v 2>&1 || true`

case "$output" in
    *"version $PKG_VERSION"*)
        ;;
    *)
        exit 1
        ;;
esac

TMP=/tmp/pkg-top-$$
trap '/bin/rm -f "$TMP"' EXIT HUP INT TERM
"$TOP" -b -d 1 5 > "$TMP" 2>&1 || {
    cat "$TMP" >&2
    exit 1
}
grep PID "$TMP" >/dev/null
