#!/bin/sh
set -e
DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin
CC=/usr/local/bin/gcc-4.2
CFLAGS='-O2 -DNeXT -D_POSIX_SOURCE'
GREP=/usr/local/bin/grep
EGREP='/usr/local/bin/grep -E'
AWK=/usr/local/bin/gawk
export PATH CC CFLAGS GREP EGREP AWK
. "$PKG_BUILD_HELPERS"
patch -p1 < "findutils-$VERSION-openstep.patch"
run_configure --prefix=/usr/local --disable-nls --disable-dependency-tracking
/bin/gnumake
/bin/gnumake install DESTDIR="$DESTDIR"
